version: "3.7"

services:
  reverseproxy:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "8080:443"
    restart: always

  api:
    depends_on:
      - reverseproxy
    build:
      context: ./DemoApi
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
